# Generated by Django 5.2.7 on 2026-01-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projects_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
