# Generated by Django 5.2.7 on 2026-01-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
